# Generated by Django 4.1.1 on 2022-10-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apix', '0007_post_commentauthors'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_signal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
